In [1]:
a = [] #for loop
for num in range(2000, 3201):
    if num % 7 == 0 and num % 5 != 0:
        a.append(num)

print(a)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [6]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)
   

In [7]:
result = factorial(5)
print(result)  


120


In [ ]:
n = int(input("Enter an integer: "))

result = {}
for i in range(1, n+1):
    result[i] = i*i

print(result)


In [10]:
def missing_char(str, n):
    return str[:n] + str[n+1:]
print(missing_char('kitten', 1)) 
print(missing_char('kitten', 0)) 
print(missing_char('kitten', 4)) 


ktten
itten
kittn


In [5]:
import numpy as np
a = np.array([[0, 1], [2, 3], [4, 5]])
b = a.tolist()
print("a:")
print("\a to list:")
print(b)


a:
 to list:
[[0, 1], [2, 3], [4, 5]]


In [6]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [8]:
import math

def calculate_Q(sequence):
    C = 50
    H = 30
    result = []
    for value in sequence:
        Q = math.sqrt((2 * C * int(value)) / H)
        result.append(round(Q))
    return result

input_sequence = input("Enter comma-separated values of D: ").split(',')
output_sequence = calculate_Q(input_sequence)
print(output_sequence)


Enter comma-separated values of D: 7,8
[5, 5]
